version: '3.2'
name: dflow

services:

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    volumes:
      - vol-postgres-data:/var/lib/postgresql/data/
    env_file:
      - .db.env
    environment:
      - SECRET_KEY=${SECRET_KEY:-Dfl0w}
      - POSTGRES_USER=${POSTGRES_USER:-dflow}
      - POSTGRES_PASSWORD=${POSTGRES_USER:-Dfl0w}
      - POSTGRES_SERVER=${POSTGRES_SERVER:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-dflow}
    ports:
      - 5432:5432
    networks:
      - dflow_net
    restart: unless-stopped

  dflow-api:
    image: dflow-api:latest
    environment:
      - SECRET_KEY=${SECRET_KEY:-Dfl0w}
      - POSTGRES_USER=${POSTGRES_USER:-dflow}
      - POSTGRES_PASSWORD=${POSTGRES_USER:-Dfl0w}
      - POSTGRES_SERVER=${POSTGRES_SERVER:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-dflow}
    networks:
      - platform_net
    restart: unless-stopped

networks:
  dflow_net:
    driver: bridge

volumes:
  vol-postgres-data:
    name: postgres-data
